image: docker:latest

stages:
  - build-baseimage
  - build-platform

before_script:
  - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PWD"

build-nsys-debian:
  stage: build-baseimage
  script:
    - cd baseimages/debian
    - docker build --pull -t nsys/debian .
    - docker push nsys/debian

build-nsys-ubuntu:
  stage: build-baseimage
  script:
    - cd baseimages/ubuntu
    - docker build --pull -t nsys/ubuntu .
    - docker push nsys/ubuntu

build-nsys:
  stage: build-platform
  script:
    - cd nsys
    - docker build --pull --no-cache -t nsys/nsys .
    - docker push nsys/nsys

build-nsys-node:
  stage: build-platform
  script:
    - cd nsys-node
    - docker build --pull --no-cache -t nsys/nsys-node .
    - docker push nsys/nsys-node
