image: docker:latest

stages:
  - build-baseimage
  - build-platform

before_script:
  - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PWD" $DOCKER_REGISTRY

build-nsys-debian:
  stage: build-baseimage
  script:
    - export DOCKER_IMAGE=nsys/debian
    - echo $DOCKER_IMAGE
    - cd baseimages/debian
    - docker build --pull -t debian .
    - docker tag debian "$DOCKER_IMAGE:latest"
    - docker push "$DOCKER_IMAGE"

build-nsys-ubuntu:
  stage: build-baseimage
  script:
    - export DOCKER_IMAGE=nsys/ubuntu
    - echo $DOCKER_IMAGE
    - cd baseimages/ubuntu
    - docker build --pull -t ubuntu .
    - docker tag ubuntu "$DOCKER_IMAGE:latest"
    - docker push "$DOCKER_IMAGE"

build-nsys:
  stage: build-platform
  script:
    - export DOCKER_IMAGE=nsys/nsys
    - echo $DOCKER_IMAGE
    - cd nsys
    - docker build --pull --no-cache -t nsys .
    - docker tag nsys "$DOCKER_IMAGE:latest"
    - docker push "$DOCKER_IMAGE"

build-nsys-node:
  stage: build-platform
  script:
    - export DOCKER_IMAGE=nsys/nsys-node
    - echo $DOCKER_IMAGE
    - cd nsys-node
    - docker build --pull --no-cache -t nsys-node .
    - docker tag nsys-node "$DOCKER_IMAGE:latest"
    - docker push "$DOCKER_IMAGE"
