image: docker:latest

stages:
  - build-baseimage
  - build-platform

before_script:
  - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PWD" $DOCKER_REGISTRY

build-nsys-debian:
  stage: build-baseimage
  script:
    - export DOCKER_IMAGE=$DOCKER_REGISTRY/nsys/debian:latest
    - echo $DOCKER_IMAGE
    - cd baseimages/debian
    - docker build --pull -t "$DOCKER_IMAGE" .
    - docker tag debian "$DOCKER_IMAGE"
    - docker push "$DOCKER_IMAGE"

build-nsys-ubuntu:
  stage: build-baseimage
  script:
    - export DOCKER_IMAGE=$DOCKER_REGISTRY/nsys/ubuntu:latest
    - echo $DOCKER_IMAGE
    - cd baseimages/ubuntu
    - docker build --pull -t "$DOCKER_IMAGE" .
    - docker tag ubuntu "$DOCKER_IMAGE"
    - docker push "$DOCKER_IMAGE"

build-nsys:
  stage: build-platform
  script:
    - export DOCKER_IMAGE=$DOCKER_REGISTRY/nsys/nsys:latest
    - echo $DOCKER_IMAGE
    - cd nsys
    - docker build --pull --no-cache -t "$DOCKER_IMAGE" .
    - docker tag nsys "$DOCKER_IMAGE"
    - docker push "$DOCKER_IMAGE"

build-nsys-node:
  stage: build-platform
  script:
    - export DOCKER_IMAGE=$DOCKER_REGISTRY/nsys/nsys-node:latest
    - echo $DOCKER_IMAGE
    - cd nsys-node
    - docker build --pull --no-cache -t "$DOCKER_IMAGE" .
    - docker tag nsys-node "$DOCKER_IMAGE"
    - docker push "$DOCKER_IMAGE"
